//! Durable graph I/O: load, provenance-keyed rewrite compaction, atomic write.
//!
//! Not LSM — there are no levels and no deferred merge. This is a
//! read-filter-rewrite of the whole file on every save, which is correct and
//! simple at the ~1.4 MB target scale (spec §3.3).

use super::model::{Edge, parse_jsonl, to_jsonl};
use std::io::Write;
use std::path::{Path, PathBuf};

/// Default location of the durable graph, relative to project root.
pub const GRAPH_REL_PATH: &str = ".phronesis/graph.jsonl";

/// Resolve the graph path for a project root.
pub fn graph_path(root: &Path) -> PathBuf {
    root.join(GRAPH_REL_PATH)
}

/// Load all edges. A missing file is an empty graph, not an error — the graph
/// is derived state and its absence simply means "nothing extracted yet".
pub fn load(path: &Path) -> std::io::Result<Vec<Edge>> {
    match std::fs::read_to_string(path) {
        Ok(body) => Ok(parse_jsonl(&body).0),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(e) => Err(e),
    }
}

/// Replace every edge whose provenance is `src` with `fresh`, and drop all
/// derived edges (they are regenerated by the derivation pass over the
/// resulting base set).
///
/// Returns the new base-edge set. Compaction keys on provenance, never on the
/// edge's subject: most subjects are functions, so subject-keyed compaction
/// would orphan edges when a function is renamed or deleted (spec §3.1).
pub fn compact(existing: Vec<Edge>, src: &str, fresh: Vec<Edge>) -> Vec<Edge> {
    let mut out: Vec<Edge> = existing
        .into_iter()
        .filter(|e| !e.d && e.src != src)
        .collect();
    out.extend(fresh.into_iter().filter(|e| !e.d));
    out
}

/// Write edges atomically: temp file in the same directory, then rename.
pub fn write_atomic(path: &Path, edges: &[Edge]) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("jsonl.tmp");
    {
        let mut f = std::fs::File::create(&tmp)?;
        f.write_all(to_jsonl(edges).as_bytes())?;
        f.sync_all()?;
    }
    std::fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn dir() -> TempDir {
        TempDir::new().unwrap()
    }

    #[test]
    fn missing_graph_file_loads_as_empty() {
        let d = dir();
        assert!(load(&graph_path(d.path())).unwrap().is_empty());
    }

    #[test]
    fn edges_survive_a_write_load_round_trip() {
        let d = dir();
        let p = graph_path(d.path());
        let edges = vec![Edge::base("imports", &["a", "b"], "a.rs")];
        write_atomic(&p, &edges).unwrap();
        assert_eq!(load(&p).unwrap(), edges);
    }

    #[test]
    fn compaction_drops_function_subject_edges_from_the_edited_file() {
        // The orphan case: subject is a function, provenance is the file.
        let existing = vec![
            Edge::base("calls_api", &["crate::f", "std::unwrap"], "src/f.rs"),
            Edge::base("calls_api", &["crate::g", "std::unwrap"], "src/g.rs"),
        ];
        let out = compact(existing, "src/f.rs", vec![]);
        assert_eq!(out.len(), 1, "edge from src/f.rs must be dropped");
        assert_eq!(out[0].a[0], "crate::g");
    }

    #[test]
    fn compaction_keeps_edges_from_other_files() {
        let existing = vec![Edge::base("imports", &["a", "b"], "other.rs")];
        let out = compact(existing.clone(), "src/f.rs", vec![]);
        assert_eq!(out, existing);
    }

    #[test]
    fn compaction_inserts_the_fresh_edge_set() {
        let fresh = vec![Edge::base(
            "defines_fn",
            &["src/f.rs", "crate::h"],
            "src/f.rs",
        )];
        let out = compact(vec![], "src/f.rs", fresh.clone());
        assert_eq!(out, fresh);
    }

    #[test]
    fn compaction_discards_all_derived_edges_wholesale() {
        let existing = vec![
            Edge::derived("no_direct_test", &["crate::g"]),
            Edge::base("imports", &["a", "b"], "other.rs"),
        ];
        let out = compact(existing, "src/f.rs", vec![]);
        assert_eq!(out.len(), 1);
        assert!(
            out.iter().all(|e| !e.d),
            "derived edges must not survive compaction"
        );
    }

    #[test]
    fn compaction_refuses_to_persist_derived_edges_supplied_as_fresh() {
        let fresh = vec![Edge::derived("no_direct_test", &["crate::h"])];
        assert!(compact(vec![], "src/f.rs", fresh).is_empty());
    }

    #[test]
    fn atomic_write_leaves_no_temp_file_behind() {
        let d = dir();
        let p = graph_path(d.path());
        write_atomic(&p, &[Edge::base("imports", &["a", "b"], "a.rs")]).unwrap();
        assert!(!p.with_extension("jsonl.tmp").exists());
    }

    #[test]
    fn rewriting_replaces_rather_than_appends() {
        let d = dir();
        let p = graph_path(d.path());
        write_atomic(&p, &[Edge::base("imports", &["a", "b"], "a.rs")]).unwrap();
        write_atomic(&p, &[Edge::base("imports", &["c", "d"], "c.rs")]).unwrap();
        let loaded = load(&p).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].a[0], "c");
    }
}
